services:
  - type: web
    name: agricola-vue
    runtime: static
    buildCommand: pnpm install && pnpm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
